name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger:
  branches:
    include:
      - main
    exclude:
      - rel/old*
  paths:
    include:
      - '*'

variables:
  - name        : poolName
    displayName : Pool
    type        : string
    default     : 'On-premise Pool'
    values      :
      - 'Azure Pipelines'
      - 'On-premise Pool'
  - name        : vmImageName
    displayName : VM
    type        : string
    default     : 'macos-latest'
    values      :
      - 'macos-latest'

stages:
  - template: 'stages/build.yaml'
    parameters:
      name      : Build
      poolName  : $(poolName)
      vmImage   : $(vmImageName)
      pipelineEnvironmentVariables  : '../environment_variables/build.yaml'    