name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger:
  branches:
    include:
      - main
    exclude:
      - rel/old*
  paths:
    include:
      - '*'

variables:
  - name  : poolName
    value : 'Azure Pipelines'
  - name  : vmImageName
    value : 'macos-latest'

stages:
  - template: 'stages/build.yaml'
    parameters:
      name      : Build
      poolName  : $(poolName)
      vmImage   : $(vmImageName)
      pipelineEnvironmentVariables  : '../environment_variables/build.yaml'    