name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger:
  branches:
    include:
      - main
    exclude:
      - rel/old*
  paths:
    include:
      - '*'

parameters:
  - name        : poolName
    displayName : Pool
    type        : string
    default     : 'Azure Pipelines'
    values      :
      - 'Azure Pipelines'
      - 'On-premise Pool'
  - name        : vmImageName
    displayName : VM
    type        : string
    default     : 'macos-latest'
    values      :
      - 'macos-latest'

stages:
  - template: 'stages/build.yaml'
    parameters:
      name      : Build
      poolName  : ${{ parameters.poolName }}
      vmImage   : ${{ parameters.vmImageName }}
      pipelineEnvironmentVariables  : '../environment_variables/build.yaml'    