name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runs_on:
        required: false
        type: string
        default: 'ubuntu-latest'
        description: 'Runner to use for the job'

jobs:
  build:
    runs-on: ${{ inputs.runs_on || 'ubuntu-latest' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set version number
        run: |
          YEAR=$(date +'%y')
          MONTH=$(date +'%m')
          DAY=$(date +'%d')
          REV=$(printf "%02d" ${{ github.run_number }})
          VERSION="$YEAR.$MONTH.$DAY.$REV"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: pdate version (gradle & plugin.xml)
        shell: bash
        run: ./update-version.sh ${{ env.VERSION }}

      - name: install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: install Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          architecture: 'x64'
          distribution: 'oracle'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :prepareSandbox -PPluginVersion=${{ env.VERSION }}
